name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Collect docker meta
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: pikrakowski/para-cli
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          outputs: type=docker
          tags: pikrakowski/para-cli:test
          labels: ${{ steps.docker-metadata.outputs.labels }}
      - name: Save docker image
        run: docker save -o docker-image.tar pikrakowski/para-cli:test
      - name: Upload docker-image.tar
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: docker-image.tar
          if-no-files-found: error
          retention-days: 1
  test-docker-image:
    name: Test docker image
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Download docker-image.tar
        uses: actions/download-artifact@v3
        with:
          name: docker-image
      - name: Load images
        run: docker load --input docker-image.tar
      - name: Test container up
        run: docker run --rm pikrakowski/para-cli:test hostname
      - name: Test npm
        run: docker run --rm pikrakowski/para-cli:test sh -c "npm version"
      - name: Test para-cli
        run: docker run --rm pikrakowski/para-cli:test sh -c "para-cli --version"
  cleanup-artifacts:
    name: Cleanup artifacts
    runs-on: ubuntu-latest
    needs: [ build-docker-image, test-docker-image ]
    steps:
      - name: Cleanup docker-image.tar
        uses: geekyeggo/delete-artifact@v1
        with:
          name: docker-image
